#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: emulators
# name: ePSXe
# image: epsxe
# info_en: An emulator for the PlayStation console that allows users to play PS1 games on their PCs, providing excellent graphics and compatibility with most games. It supports various plugins to enhance sound and video, as well as features for saving and loading games at any moment.
# info_ru: Эмулятор для консоли PlayStation, который позволяет пользователям играть в игры для PS1 на ПК, обеспечивая отличную графику и совместимость с большинством игр. Он поддерживает различные плагины для улучшения звука и видео, а также функции сохранения и загрузки игр в любой момент.
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/ePSXe205.zip"
start_portwine
if try_download "https://www.epsxe.com/files/ePSXe205.zip" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/ePSXe"
    PW_EXE_FILE="$WINEPREFIX/drive_c/Program Files (x86)/ePSXe/ePSXe.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    kill_portwine
    export PORTWINE_CREATE_SHORTCUT_NAME="ePSXe"
    portwine_create_shortcut
fi
stop_portwine
