#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: GameXP
# image: gamexp
# info_en: Launcher for GameXP studio games.
# info_ru: Лаунчер для игр GameXP.
########################################################################
export PW_PREFIX_NAME="GAMEXP"
export LAUNCH_PARAMETERS="/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-"
export PW_AUTOINSTALL_EXE="${PORT_WINE_TMP_PATH}/InstallGameXPlauncher.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="GameXP"

start_portwine
if try_download "https://clotho-install.gamexp.com/launcher/InstallGameXPlauncher-0-pr.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_kill_autostart gamexp-launcher.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    PW_EXE_FILE="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/Programs/GameXP/Launcher/gamexp-launcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine
