#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: games
# name: ITCH.IO
# image: itch
# info_en: Launcher for the library of indie games.
# info_ru: Лаунчер для библиотеки инди-игр.
##########################################################################
export LAUNCH_PARAMETERS="--silent"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/itch-setup.exe"

start_portwine
if try_download "https://itch.io/app/download?platform=windows" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_kill_autostart itch.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    PW_EXE_FILE=$(find "$WINEPREFIX/drive_c/users" -type f -name "itch.exe")
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    kill_portwine
    export PORTWINE_CREATE_SHORTCUT_NAME="Itch"
    portwine_create_shortcut
fi
stop_portwine
