#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: Panzar
# image: panzar
# info_en: A multiplayer online action game where players battle in teams using various character classes and unique abilities. The game features tactical battles on large maps with destructible environments.
# info_ru: Многопользовательская онлайн-игра в жанре экшен, где игроки сражаются в командах, используя различные классы персонажей и уникальные способности. Игра предлагает тактические сражения на больших картах с разрушительным взаимодействием окружения.
########################################################################
export LAUNCH_PARAMETERS="/VERYSILENT"
export PW_WINDOWS_VER="7"
export PW_PREFIX_NAME="PANZAR"
export PW_AUTOINSTALL_EXE="${PORT_WINE_TMP_PATH}/Panzar.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="Panzar"

start_portwine
if try_download "https://www.panzar.ru/ru/download/installer/" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_kill_autostart start.exe 3 &
    pw_run "${PW_AUTOINSTALL_EXE}"
    export PW_EXE_FILE="${WINEPREFIX}/drive_c/Games/Panzar/start.exe"
    pw_create_unique_exe
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine
