#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: Secret World Legends (ENG)
# image: swl
# info_en: An MMORPG with a unique story and setting based on myths, legends, and secret societies, allowing players to explore a modern world filled with supernatural beings and mysteries. The game offers freedom in skill selection and character building, along with engaging quests and a rich narrative.
# info_ru: MMORPG с уникальной историей и сеттингом, основанная на мифах, легендах и тайных обществах, позволяющая игрокам исследовать современный мир, полный сверхъестественных существ и загадок. Игра предлагает свободу в выборе навыков и построении персонажей, а также захватывающие квесты и глубокий сюжет.
########################################################################
export WINEDLLOVERRIDES="d3d9=b"
export LAUNCH_PARAMETERS="/VERYSILENT"
export PW_AUTOINSTALL_EXE="${PORT_WINE_TMP_PATH}/SecretWorldLegendsMin.exe"
export PW_PREFIX_NAME="SECRET_WORLD_LEGENDS"

start_portproton
if try_download "https://web-cdn.funcom.com/downloads/swl/SecretWorldLegendsMin.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_kill_autostart ClientPatcher.exe &
#    pw_kill_autostart PatcherSetup.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
#    PW_EXE_FILE="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/SecretWorldLegendsDX11.exe"
    PW_EXE_FILE="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/ClientPatcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    kill_portwine
    export PORTWINE_CREATE_SHORTCUT_NAME="Secret World Legends"
    portwine_create_shortcut
fi
stop_portproton
