#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: games
# name: VK Play Games Center
# image: mygames
# info_en: Launcher for the VK Play game library.
# info_ru: Лаунчер для библиотеки игр VK Play.
########################################################################
export PW_PREFIX_NAME="VK_PLAY"
# export LAUNCH_PARAMETERS=""
export PW_AUTOINSTALL_EXE="${PORT_DATA_PATH}/data/prefixes/${PW_PREFIX_NAME}/drive_c/users/steamuser/AppData/Local/VKPlayLoader.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="VK Play"

export WINEDLLOVERRIDES="mscoree,mshtml="
export PW_MUST_HAVE_DLL=""
export PW_WINE_USE="WINE_LG"

start_portproton
if try_download "https://static.gc.vkplay.ru/VKPlayLoader.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    PW_EXE_FILE="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/VKPlayLoader.exe"
    try_remove_file "${PW_EXE_FILE}.ppdb"
    portwine_create_shortcut
fi
stop_portproton
