name: Build AppImage, Arch and Fedora Packages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]*.[0-9]*'

env:
  # Common version, will be used for tagging the release
  VERSION: 1.0
  PKGDEST: "/tmp/portprotonqt"
  PACKAGE: "portprotonqt"
  GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}

jobs:
  build-appimage:
    name: Build AppImage
    runs-on: ubuntu-22.04
    container:
      image: archlinux:base-devel
      options: --privileged --device /dev/fuse
    steps:
      - name: Prepare container
        run: |
          pacman-key --init
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm --disable-download-timeout --needed git wget gnupg nodejs npm xorg-server-xvfb zsync

      - uses: https://gitea.com/actions/checkout@v4

      - name: Install appimage dependencies
        run: |
          cd build-aux/AppImage
          chmod +x get-dependencies.sh portprotonqt-appimage.sh
          ./get-dependencies.sh

      - name: Build AppImage
        run: |
          cd build-aux/AppImage
          ./portprotonqt-appimage.sh

      - name: Upload AppImage
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: PortProtonQt-AppImage
          path: build-aux/AppImage/dist/*.AppImage

  build-arch:
    name: Build Arch Package
    runs-on: ubuntu-22.04
    container:
      image: archlinux:base-devel

    steps:
      - name: Prepare container
        run: |
          pacman -Syuu --noconfirm --disable-download-timeout --needed git wget gnupg nodejs npm
          sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc) -l$(nproc)"/g' /etc/makepkg.conf
          sed -i 's/OPTIONS=(.*)/OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge lto)/g' /etc/makepkg.conf
          yes | pacman -Scc
          pacman-key --init
          pacman -S --noconfirm archlinux-keyring
          mkdir -p /__w/portproton-repo
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
          cat << EOM >> /etc/pacman.conf

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist
          EOM
          pacman -Syy
          useradd -m user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          echo "PACKAGER=\"Boris Yumankulov <boria138@altlinux.org>\"" >> /etc/makepkg.conf
          chown user -R /tmp
          chown user -R ..

      - name: Checkout
        uses: https://gitea.com/actions/checkout@v4

      - name: Build
        run: |
          cd /__w/portproton-repo
          cp -r "$GITHUB_WORKSPACE" PortProtonQt
          cd /__w/portproton-repo/PortProtonQt/build-aux
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Upload Arch package
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: PortProtonQt-Arch
          path: ${{ env.PKGDEST }}/*

  build-fedora:
    name: Build Fedora RPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fedora_version: [42, 43, 44, rawhide]

    container:
      image: fedora:${{ matrix.fedora_version }}
      options: --privileged

    steps:
      - name: Install build dependencies
        run: |
          dnf install -y git rpmdevtools meson ninja-build python3-devel \
                         systemd-rpm-macros vulkan-loader-devel redhat-rpm-config nodejs npm \
                         gcc gettext

      - name: Setup rpmbuild environment
        run: |
          useradd rpmbuild -u 5002 -g users || true
          mkdir -p /home/rpmbuild/{BUILD,RPMS,SPECS,SRPMS,SOURCES}
          chown -R rpmbuild:users /home/rpmbuild
          echo '%_topdir /home/rpmbuild' > /home/rpmbuild/.rpmmacros

      - name: Checkout repo
        uses: https://gitea.com/actions/checkout@v4

      - name: Copy fedora.spec
        run: |
          cp build-aux/fedora.spec /home/rpmbuild/SPECS/${{ env.PACKAGE }}.spec
          chown -R rpmbuild:users /home/rpmbuild

      - name: Build RPM
        run: |
          su rpmbuild -c "rpmbuild -ba /home/rpmbuild/SPECS/${{ env.PACKAGE }}.spec"

      - name: Upload RPM package
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: PortProtonQt-RPM-Fedora-${{ matrix.fedora_version }}
          path: /home/rpmbuild/RPMS/**/*.rpm

  release:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.com/actions/checkout@v4

      - name: Install required dependencies
        run: |
            sudo apt update
            sudo apt install -y original-awk unzip

      - name: Download all artifacts
        uses: https://gitea.com/actions/download-artifact@v3
        continue-on-error: true
        with:
          path: release/

      - name: Extract downloaded artifacts
        run: |
          mkdir -p extracted
          find release/ -name '*.zip' -exec unzip -o {} -d extracted/ \;
          find extracted/ -type f -exec mv {} release/ \;
          find release/ -name '*.zip' -delete
          rm -rf extracted/

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION="${{ env.VERSION }}"
          awk "/^## \\[$VERSION\\]/ {flag=1; next} /^## \\[/ || /^---/ {flag=0} flag" CHANGELOG.md > changelog.txt

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@v1
        env:
            NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          body_path: changelog.txt
          token: ${{ env.GITEA_TOKEN }}
          tag_name: v${{ env.VERSION }}
          prerelease: false
          files: release/**/*
          sha256sum: false
