name: Check Translations
run-name: Check spelling in translation files
on:
  push:
    branches: [main]
    paths:
      - 'portprotonqt/locales/**'
  pull_request:
    paths:
      - 'portprotonqt/locales/**'
  workflow_dispatch:

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://gitea.com/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Python
        uses: https://gitea.com/actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install Python dependencies
        run: pip install pyaspeller babel

      - name: Run spell check
        run: python dev-scripts/l10n.py --spellcheck
