name: Check Translations (disabled until yaspeller is fixed)
run-name: Check spelling in translation files
on:
  push:
    branches: [main]
    paths:
      - 'portprotonqt/locales/**'
  pull_request:
    paths:
      - 'portprotonqt/locales/**'
  workflow_dispatch:

jobs:
  check-translations:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://gitea.com/actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Python
        uses: https://gitea.com/actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install Python dependencies
        run: pip install pyaspeller babel

      - name: Run spell check
        run: python dev-scripts/l10n.py --spellcheck
