name: Code check

on:
  pull_request:
    branches: [main, scripts]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
      - "portprotonqt/locales/**"
  push:
    branches: [main, scripts]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
      - "portprotonqt/locales/**"
  workflow_dispatch:

jobs:
  pre-commit:
    name: Check code
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel@sha256:0cf5eb78f8c3ddcdd7ccc3f9168328fb57ec6be0f83f501a0b2006590e0c92ec
    steps:
      - name: Install system dependencies
        run: |
          pacman -Syuu --noconfirm --disable-download-timeout
          pacman -S --noconfirm --needed git nodejs npm mesa libarchive sdl3 pyside6 qt6-svg qt6-imageformats uv
          pacman -Scc --noconfirm

      - uses: https://git.linux-gaming.ru/actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Sync dependencies into venv
        run: uv sync --all-extras --dev

      - name: Activate .venv & run pre-commit
        shell: bash
        run: |
          source .venv/bin/activate
          pre-commit run --show-diff-on-failure --color=always --all-files
