name: Code check

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
  push:
    branches: [main]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
  workflow_dispatch:

jobs:
  pre-commit:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node.js
        uses: https://gitea.com/actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install uv manually
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source $HOME/.local/bin/env
          uv --version

      - name: Sync dependencies into venv
        run: uv sync --all-extras --dev

      - name: Activate .venv & run pre-commit
        shell: bash
        run: |
          source .venv/bin/activate
          pre-commit run --show-diff-on-failure --color=always --all-files
