name: Download stats

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: {}

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.linux-gaming.ru/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Update download stats
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_ACTOR: ${{ gitea.actor }}
          GITEA_SERVER: "git.linux-gaming.ru"
          GITEA_REPOSITORY: ${{ gitea.repository }}
        run: bash dev-scripts/get_download_stats.sh
