# Adwaita Theme
foreground #eeeeec
background #1e1e1e
selection_foreground #ffffff
selection_background #3584e4
background_opacity 1.0
cursor_shape block
enable_audio_bell no

# Black
color0 #1e1e1e
color8 #555753
# Red
color1 #cc0000
color9 #ef2929
# Green
color2 #4e9a06
color10 #8ae234
# Yellow
color3 #c4a000
color11 #fce94f
# Blue
color4 #3465a4
color12 #729fcf
# Magenta
color5 #75507b
color13 #ad7fa8
# Cyan
color6 #06989a
color14 #34e2e2
# White
color7 #d3d7cf
color15 #eeeeec

font_size 14
font_family Monospace
