"""Steam API module for PortProtonQt."""

from portprotonqt.steam_api.utils import (
    safe_vdf_load,
    decode_text,
    get_cache_dir,
    get_steam_home,
    get_steam_compat_tool,
    get_steam_libs,
    get_playtime_data,
    get_steam_installed_games,
    normalize_name,
    is_valid_candidate,
    filter_candidates,
    remove_duplicates,
    convert_steam_id,
    get_last_steam_user,
)
from portprotonqt.steam_api.cache import (
    get_exiftool_data,
    delete_cached_app_files,
    load_app_details,
    save_app_details,
    load_protondb_status,
    save_protondb_status,
    build_index,
    build_weanticheatyet_index,
    search_app,
    search_anticheat_status,
)
from portprotonqt.steam_api.api import (
    fetch_sgdb_cover,
    check_url_exists,
    fetch_app_info_async,
    get_protondb_tier_async,
    get_full_steam_game_info_async,
    get_steam_game_info_async,
    get_steam_apps_and_index_async,
    get_anticheat_data_and_index_async,
    get_weanticheatyet_status_async,
    clear_steam_api_caches,
)
from portprotonqt.steam_api.shortcuts import (
    enable_steam_cef,
    call_steam_api,
    add_to_steam,
    remove_from_steam,
    is_game_in_steam,
)

__all__ = [
    # Utils
    "safe_vdf_load",
    "decode_text",
    "get_cache_dir",
    "get_steam_home",
    "get_steam_compat_tool",
    "get_steam_libs",
    "get_playtime_data",
    "get_steam_installed_games",
    "normalize_name",
    "is_valid_candidate",
    "filter_candidates",
    "remove_duplicates",
    "convert_steam_id",
    "get_last_steam_user",
    # Cache
    "get_exiftool_data",
    "delete_cached_app_files",
    "load_app_details",
    "save_app_details",
    "load_protondb_status",
    "save_protondb_status",
    "build_index",
    "build_weanticheatyet_index",
    "search_app",
    "search_anticheat_status",
    # API
    "fetch_sgdb_cover",
    "check_url_exists",
    "fetch_app_info_async",
    "get_protondb_tier_async",
    "get_full_steam_game_info_async",
    "get_steam_game_info_async",
    "get_steam_apps_and_index_async",
    "get_anticheat_data_and_index_async",
    "get_weanticheatyet_status_async",
    "clear_steam_api_caches",
    # Shortcuts
    "enable_steam_cef",
    "call_steam_api",
    "add_to_steam",
    "remove_from_steam",
    "is_game_in_steam",
]
