# Install PortProtonQt Steam compatibility tool
install_data(
  'compatibilitytool.vdf',
  'toolmanifest.vdf',
  install_dir: prefix / get_option('datadir') / 'steam' / 'compatibilitytools.d' / 'PortProtonQt',
)

install_data(
  'portproton',
  install_dir: prefix / get_option('datadir') / 'steam' / 'compatibilitytools.d' / 'PortProtonQt',
  install_mode: 'rwxr-xr-x',
)
